dj_rpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.landing_page, name='landing_page'),
    path('', include('users.urls', namespace='users')),  
    path('', include('appointments.urls', namespace='appointments')),  


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('user_role/', views.get_user_role, name='user_role'),
    path('signup/', views.signup_view, name='signup'),
    path('register_patient/', views.patient_signup_view, name='patient_signup'),
    path('register_doctor/', views.doctor_signup_view, name='doctor_signup'),
    
    # * Patient pages
    path('patient/<int:patient_id>/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/<int:patient_id>/profile/', views.patient_profile, name='patient_profile'),
    path('patient/<int:patient_id>/maps/', views.maps, name='maps'),

    # * Doctor pages
    path('doctor/<int:doctor_id>/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctors/delete_patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    path('doctor/<int:doctor_id>/profile/', views.doctor_profile, name='doctor_profile'),

]

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model

from .models import Patient, Doctor, Pharmacist, LabTechnician

User = get_user_model()

# class UserCreationForm(forms.ModelForm):
#     # role = forms.ChoiceField(widget=forms.RadioSelect, choices=[(1, 'Patient'), (2, 'Doctor')])
#     class Meta:
#         model = User
#         fields = ('email', 'password, ')

class PatientCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
    class Meta:
        model  = Patient
        fields = '__all__'

class DoctorCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
    class Meta:
        model  = Doctor
        fields = '__all__'


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'role')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'active', 'admin', 'role')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class PatientHealthUpdateForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = (
            'date_of_birth',
            'age', 
            'gender',     
            'weight',     
            'height',     
            'blood_group',
            'country',    
            'city',       
            'street',     
        )

class PatientPersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'personal_image')


class DoctorUpdateForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = (
            'specialist',
            'gender',
        )

class DoctorPersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'personal_image')

users/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from random import randint
from .forms import (
    UserAdminCreationForm,
    # UserCreationForm,
    PatientCreationForm,
    DoctorCreationForm,
    PatientHealthUpdateForm,
    PatientPersonalUpdateForm,
    DoctorUpdateForm,
    DoctorPersonalUpdateForm,
)
from .models import Patient, Doctor, User, UserManager

from appointments.models import Appointment
from appointments.views import patient_appointments, doctor_appointments

User = get_user_model()


def landing_page(request):
    return render(request, 'landing_page.html')


def signup_view(request):
    form = UserAdminCreationForm()  # GET REQUEST
    if request.method == 'POST':
        form = UserAdminCreationForm(request.POST)
        print(form)
        if form.is_valid():

            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            form.save()

            # Check user role
            if form.cleaned_data['role'] == 'Patient':
                patient_signup_view(request)
                return redirect('/register_patient/')
            elif form.cleaned_data['role'] == 'Doctor':
                doctor_signup_view(request)
                return redirect('/register_doctor/')

        else:
            messages.error(request, "You must select a role")

    return render(request, 'registration/signup.html', {'form': form})


def patient_signup_view(request):
    initial_data = {
        'patient': User.objects.last()
    }
    form = PatientCreationForm(initial=initial_data)

    if request.method == 'POST':
        form = PatientCreationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            patient = User.objects.filter(
                role='Patient').order_by('-date_joined').first()
            supervised_by = form.cleaned_data['supervised_by']
            date_of_birth = form.cleaned_data['date_of_birth']
            age = form.cleaned_data['age']
            gender = form.cleaned_data['gender']
            weight = form.cleaned_data['weight']
            height = form.cleaned_data['height']
            country = form.cleaned_data['country']
            city = form.cleaned_data['city']
            street = form.cleaned_data['street']
            print(f"### {patient}")
            new_patient = Patient.objects.create(
                patient=patient,
                supervised_by=supervised_by,
                date_of_birth=date_of_birth,
                age=age,
                gender=gender,
                weight=weight,
                height=height,
                country=country,
                city=city,
                street=street,
            )

            patient.save(new_patient)
            return redirect('/login/')
        else:
            messages.error(
                request, "Make sure to complete the form before submitting it!")
    return render(request, 'registration/patient_signup.html', {'form': form})


def doctor_signup_view(request):
    initial_data = {
        'doctor': User.objects.last()
    }
    form = DoctorCreationForm(initial=initial_data)

    if request.method == 'POST':
        form = DoctorCreationForm(request.POST)

        if form.is_valid():
            doctor = User.objects.order_by('-date_joined').first()
            specialist = form.cleaned_data['specialist']
            new_doctor = Doctor.objects.create(
                doctor=doctor, specialist=specialist)
            Doctor.save(new_doctor)
            return redirect('/login/')
        else:
            print("Invalid")
    return render(request, 'registration/doctor_signup.html', {'form': form, })


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                # user: is an email.
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                # If the logged in user is patient redirect them for patient dashboard
                # other wise to doctor dashboard
                # TODO: Users [Admin, Doctor, Patient] redirected to patient Dashboard after logging.
                # TODO: It need's to be fixed by tonight.

                if User.objects.get(email=user).admin == True:
                    # Admin user/admin/'
                    return redirect('http://127.0.0.1:8000/admin/')
                elif User.objects.get(email=user).role == 'Patient':
                    # patient user
                    return redirect('users:patient_dashboard', user.Patient.id)
                elif User.objects.get(email=user).role == 'Doctor':
                    return redirect('users:doctor_dashboard', user.Doctor.id)

            else:
                messages.error(request, 'Cannot submit empty instance!')
        else:
            messages.error(request, 'Invalid email or password.')
    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})


def logout_view(request):
    logout(request)
    # messages.info(request, 'You have been logged out.')
    return redirect('/')


# PATIENT DASHBAORD FUNCTIONS
@login_required
def patient_dashboard(request, patient_id):
    try:
        patient = Patient.objects.get(id=patient_id)
    except:
        raise Http404

    gender, height, weight, age = (
        patient.gender,
        patient.height,
        patient.weight,
        patient.age,
    )

    # Custom values
    body_mass_index = round(weight / ((height / 100) ** 2), 2)
    diabetes_level = randint(140, 200)
    blood_pressure = {
        'systolic': randint(120, 140),
        'diastolic': randint(80, 90),
    }
    steps = randint(1000, 10000)

    details_card = {
        'Age': str(age) + ' Year',
        'Blood Group': patient.blood_group,
        'Height': str(height) + ' cm',
        'Weight': str(weight) + ' kg',
    }

    # Get all the appointments for this patient from appointments views
    appointments = patient_appointments(patient_id)
    context = {
        'patient': patient,
        'gender': gender,
        'height': height,
        'weight': weight,
        'age': age,
        'bmi': body_mass_index,
        'diabetes_level': diabetes_level,
        'blood_pressure': blood_pressure,
        'steps': steps,
        'details_card': details_card,
        'title': 'Dashboard',
        'appointments': appointments
    }
    # print(appointments)
    return render(request, 'users/patient/dashboard_content.html', context)


@login_required
def maps(request, patient_id):
    # Return all the clinics in a 'city' in google maps.
    patient = Patient.objects.get(id=patient_id)
    country = patient.country
    city = patient.city

    context = {
        'country': country,
        'city': city,
        'title': 'Map',

    }
    return render(request, 'users/patient/map.html', context)


@login_required
def patient_profile(request, patient_id):

    if request.method == 'POST':
        personal_form = PatientPersonalUpdateForm(
            request.POST, request.FILES, instance=request.user)
        health_form = PatientHealthUpdateForm(
            request.POST, instance=request.user.Patient)

        if personal_form.is_valid() and health_form.is_valid():
            print(personal_form)
            personal_form.save()
            health_form.save()
            messages.success(
                request, f"Your account has been upadted successfully.")
            return redirect("users:patient_profile", request.user.Patient.id)
        else:
            messages.error(
                request, "Error: Please make sure to enter valid data")

    else:
        personal_form = PatientPersonalUpdateForm(instance=request.user)
        health_form = PatientHealthUpdateForm(instance=request.user.Patient)

    context = {
        'p_form': personal_form,
        'h_form': health_form
    }

    return render(request, 'users/patient/profile.html', context)
# END PATIENT VIEWS


# DOCTOR DASHBAORD FUNCTIONS
@login_required
def doctor_dashboard(request, doctor_id):
    doctor = Doctor.objects.get(id=doctor_id)
    patients = doctor.patient_set.all()

    appointments = doctor_appointments(doctor_id)

    context = {
        'patients': patients,
        'appointments': appointments,
    }
    return render(request, 'users/doctor/dashboard_content.htm', context)


@login_required
def delete_patient(request, patient_id):
    current_doctor = Doctor.objects.get(doctor=request.user.id)
    patient = current_doctor.patient_set.get(id=patient_id)
    # ? Cut the relationship between doctor and patient, but do not delete patient
    Patient.objects.filter(id=patient_id).update(supervised_by=None)
    messages.success(request, f"{patient} has been removed.")
    return redirect("users:doctor_dashboard", request.user.Doctor.id)


@login_required
def doctor_profile(request, doctor_id):
    if request.method == 'POST':
        personal_form = DoctorPersonalUpdateForm(
            request.POST, request.FILES, instance=request.user)
        doctor_form = DoctorUpdateForm(
            request.POST, instance=request.user.Doctor)
        if personal_form.is_valid() and doctor_form.is_valid():
            print(personal_form)
            personal_form.save()

users/templates/users/doctor/dashboard_content.htm
{% extends 'users/doctor/doctor_base.html' %}
{% load static %}
{% block content %}

{% if messages %}
{% for msg in messages %}
<div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
    <!-- <strong class="font-bold"></strong> -->
    <span class="block sm:inline">{{msg}}</span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20">
            <title>Close</title>
            <path
                d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
        </svg>
    </span>
</div>
{% endfor %}
{% endif %}



<link rel="stylesheet" href="{% static 'css/dashboard.css' %}" type="text/css">
<!-- chartjs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"
    integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
    crossorigin="anonymous">
</script>

<div class="content-section">

    <section class="header-section">
        <div class="user-card shadow">
            <div class="card-text">
                <h1>Hello Dr.{{user.get_full_name}}</h1>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
            </div>
            <img class="tree-img" src="{% static 'images/icons/trees_2.png' %}" alt="">
        </div>

        <div class="info-card shadow">
            <div class="info-detail">
                <div>
                    <div class="number first"><span>32</span></div>
                    <div class="description">Important Tasks</div>
                </div>

                <div>
                    <div class="number second"><span>21</span></div>
                    <div class="description">New Patients</div>
                </div>

                <div>
                    <div class="number third"><span>19</span></div>
                    <div class="description">Alart</div>
                </div>
            </div>
        </div>
    </section>

    <section class="main-section">
        <div class="activity-chart ">
            <canvas class="shadow" id="activity-chart"></canvas>
            <script>
                var ctx = document.getElementById('activity-chart').getContext("2d")
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                        datasets: [{
                            label: "Consultation",
                            borderColor: "rgba(255, 99, 132, 0.9)",
                            pointBorderColor: "rgba(255, 99, 132, 0.9)",
                            pointBackgroundColor: "rgba(255, 99, 132, 0.9)",
                            pointHoverBackgroundColor: "rgba(255, 99, 132, 0.9)",
                            pointHoverBorderColor: "rgba(255, 99, 132, 0.1)",
                            pointBorderWidth: 10,
                            pointHoverRadius: 10,
                            pointHoverBorderWidth: 10,
                            pointRadius: 3,
                            fill: false,
                            borderWidth: 2,
                            data: [40, 28, 43, 63, 41, 60],
                        }, {
                            label: "New Patietns",
                            borderColor: "rgba(	27, 80, 100, 0.9)",
                            pointBorderColor: "rgba(27, 80, 100, 0.9)",
                            pointBackgroundColor: "rgba(27, 80, 100, 0.9)",
                            pointHoverBackgroundColor: "rgba(27, 80, 100, 0.9)",
                            pointHoverBorderColor: "rgba(27, 80, 100, 0.9)",
                            pointBorderWidth: 10,
                            pointHoverRadius: 10,
                            pointHoverBorderWidth: 10,
                            pointRadius: 3,
                            fill: false,
                            borderWidth: 2,
                            data: [27, 58, 23, 23, 55, 40],
                        }]
                    },
                    options: {
                        legend: {
                            position: "top"
                        },
                        scales: {
                            yAxes: [{
                                ticks: {
                                    fontColor: "rgba(0,0,0,0.5)",
                                    fontStyle: "bold",
                                    beginAtZero: true,
                                    maxTicksLimit: 8,
                                    padding: 20,
                                },
                                gridLines: {
                                    drawTicks: true,
                                    display: true
                                }
                            }],
                            xAxes: [{
                                gridLines: {
                                    zeroLineColor: "rgba(0,0,0,0.1)"
                                },
                                ticks: {
                                    padding: 20,
                                    fontColor: "rgba(0,0,0,0.5)",
                                    fontStyle: "bold"
                                },
                                gridLines: {
                                    drawTicks: true,
                                    display: false
                                }
                            }]
                        }
                    }
                });


                myChart.canvas.parentNode.style.height = '40%';
                myChart.canvas.parentNode.style.width = '63%';
            </script>
        </div>

        <div class="detail-card shadow">
            <h1 class="title">Recent Patients</h1>

            {% if patients %}
            {% for patient in patients %}
            <div class="user-detail mb-3">
                <img class="image rounded-image" src="/media/default.jpg" alt="patient_default_image">
                <div class="user-detail-cointainer">
                    <h3 class="user-name">{{patient.patient.get_full_name}}</h3>
                    <h4 class="case">Eye Probelm</h4>
                </div>

                <div class="icons-container">
                    <a class="mail" href="mailto:{{patient.patient}}">
                        <img src="{% static 'images/icons/mail.png' %}" alt="mail">
                    </a>
                    <a class="delete" href="{% url 'users:delete_patient' patient.id %}">
                        <img src="{% static 'images/icons/x-mark.png' %}" alt="mail">
                    </a>
                </div>
            </div>

            {% endfor %}
            {% else %}
            <h1 class="no-patients">You have no patients yet.</h1>
            {% endif %}
        </div>
    </section>

    <section class="charts-section flex-wrapper">
        <div class="chart shadow">
            <h1 class="title">Dieases Report</h1>
            <canvas id="dieases-report"></canvas>
            <script>
                var ctx = document.getElementById("dieases-report");
                var myChart = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: ['Flo', 'Eye Problem', 'Diabetis', 'Colds'],
                        datasets: [{
                            label: 'Dieases Report',
                            data: [12, 19, 3, 5],
                            backgroundColor: [
                                '#e85a79',
                                '#ffc200',
                                '#504da6',
                                '#6fd1f6'
                            ],
                            borderColor: [
                                '#e85a79',
                                '#ffc200',
                                '#504da6',
                                '#6fd1f6'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        legend: {
                            position: "bottom"
                        },
                        layout: {
                            padding: {
                                left: 0,
                                right: 0,
                                top: 10,
                                bottom: 10
                            }
                        },

                        //cutoutPercentage: 40,
                        responsive: true,

                    }
                });

                myChart.canvas.parentNode.style.height = '50%';
                myChart.canvas.parentNode.style.width = '48%';
            </script>
        </div>

        <div class="chart shadow">
            <h1 class="title">Patients Comes</h1>
            <canvas id="patients-comes"></canvas>
            <script>
                var ctx = document.getElementById("patients-comes");
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: ['Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat', 'Sun'],
                        datasets: [{
                            label: 'Male',
                            data: [24, 20, 30, 42, 52, 30, 19],
                            backgroundColor: "#2b2db3"
                        },
                        {
                            label: 'Female',
                            data: [19, 30, 21, 40, 18, 38, 42],
                            backgroundColor: "#63b8f1"
                        },
                        ]
                    },
                    options: {
                        legend: {
                            position: "bottom"
                        },
                        layout: {
                            padding: {
                                left: 0,
                                right: 0,
                                top: 10,
                                bottom: 10
                            }
                        },
                        scales: {
                            yAxes: [{
                                ticks: {
                                    fontColor: "rgba(0,0,0,0.5)",
                                    fontStyle: "bold",
                                    beginAtZero: true,
                                    maxTicksLimit: 8,
                                    padding: 20,
                                },
                                gridLines: {
                                    drawTicks: true,
                                    display: true
                                }
                            }],
                            xAxes: [{
                                gridLines: {
                                    zeroLineColor: "rgba(0,0,0,0.1)"
                                },
                                ticks: {
                                    padding: 0,
                                    fontColor: "rgba(0,0,0,0.5)",
                                    fontStyle: "bold"
                                },
                                gridLines: {
                                    drawTicks: true,
                                    display: false
                                }
                            }]
                        },

                        //cutoutPercentage: 40,
                        responsive: true,

                    }
                });

                myChart.canvas.parentNode.style.height = '50%';
                myChart.canvas.parentNode.style.width = '48%';
            </script>
        </div>
    </section>

    
    <section class="charts-section flex-wrapper">
        <div class="chart">
                <h1 class="title">Accepted Appoinemnts</h1>
            </div>

            <div class="chart">
                <h1 class="title">Pended Appoinemnts</h1>
            </div>
    </section>


</div>
{% endblock %}

users/templates/users/doctor/doctor_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Dashboard - {{ title }}</title>
    {% else %}
    <title>Doctor Dashboard</title>
    {% endif %}
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/dashboard_layout.css' %}">
</head>

<body>
    <div class="container">

        <div class="header">
            <nav>
                <ul>
                    <!-- <li class="username">Hello Dr.{{user.get_full_name}}</li> -->
                    <a href="{% url 'users:logout' %}"
                        class="logout inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
                        Logout
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </ul>
            </nav>
        </div>
        
        <div class="sidebar">
    
            <header class="logo">
                <img src="{% static 'images/logo_transparent.png' %}" alt="logo">
            </header>
                
            <div>
                <ul>
                    <li>
                        <img class="link-icon" src="{% static 'images/icons/dashboard.png' %}" alt="">
                        <a class="nav-link {% if request.path == '/doctors/dashboard/' %} active {% endif %}" href="{% url 'users:doctor_dashboard' %}">Dashboard</a>
                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/user.png' %}" alt="">
                        <a class="nav-link" href="#">Profile</a>

                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/appoinment.png' %}" alt="">
                        <a class="nav-link" href="#">Appoinments</a>
                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/bell.png' %}" alt="">
                        <a class="nav-link" href="#">Notifications</a>
                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/drug-schedule.png' %}" alt="">
                        <a class="nav-link" href="#">Drug Schedule</a>
                    </li>

                </ul>
            </div>
        </div>
        


        <div class="content">
            {% block content %} {% endblock %}
        </div>




    </div>
</body>

</html>