appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('new_appointemnt/', views.appointment_create_view, name='new_appointemnt'),
    path('patient_appointments/', views.patient_appointments, name='patient_appointments'),
    path('requested_appointments/', views.DoctorAppointmentsListView.as_view(), name='requested_appointments'),
    path('get_appointment_status/', views.get_appointment_status, name='get_appointment_status'),
]

dj_rpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.landing_page, name='landing_page'),
    path('', include('users.urls', namespace='users')),  
    path('', include('appointments.urls', namespace='appointments')),  


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('user_role/', views.get_user_role, name='user_role'),
    path('signup/', views.signup_view, name='signup'),
    path('register_patient/', views.patient_signup_view, name='patient_signup'),
    path('register_doctor/', views.doctor_signup_view, name='doctor_signup'),
    
    # * Patient pages
    path('patient/<int:patient_id>/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/<int:patient_id>/profile/', views.patient_profile, name='patient_profile'),
    path('patient/<int:patient_id>/maps/', views.maps, name='maps'),

    # * Doctor pages
    path('doctor/<int:doctor_id>/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctors/delete_patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    path('doctor/<int:doctor_id>/profile/', views.doctor_profile, name='doctor_profile'),

]

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth import get_user_model
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image


class UserManager(BaseUserManager):
    # ? create_user( takes all the required fileds )
    def create_user(self, email, is_staff, is_admin, is_doctor=False, is_patient=False, password=None, is_active=True):

        if not password:
            raise ValueError("Users must have a password")

        if not email:
            raise ValueError("Users must have an email address")
        user_obj = self.model(
            email=self.normalize_email(email)
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.doctor = is_doctor
        user_obj.patient = is_patient
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self,  email, password=None):
        user = self.create_user(email, password=password, is_staff=True)
        return user

    def create_superuser(self,  email, password=None):
        user = self.create_user(email, password=password,
                                is_admin=True, is_staff=True)
        return user

    def create_patient(self,  email, password=None):
        user = self.create_user(email, password=password, is_patient=True)
        return user

    def create_doctor(self,  email, password=None):
        user = self.create_user(email, password=password, is_doctor=True)
        return user


class User(AbstractBaseUser):

    USER_TYPE = (
        ('Patient', 'Patient'),
        ('Doctor', 'Doctor'),
    )

    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    personal_image = models.ImageField(default='default.jpg', upload_to='user_pics')
    phone_number = PhoneNumberField(blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)  # ? Can login?
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    role = models.CharField(max_length=8, choices=USER_TYPE)

    USERNAME_FIELD = 'email'
    # * USERNAME_FIELDS(Email) and Password are required by default
    REQUIRED_FIELDS = []

    objects = UserManager()

        
    def save(self, *args, **kwargs):
        # Rewrite the save function to resize the saved images
        super().save()
        
        img = Image.open(self.personal_image.path)
        
        # Check dimensions
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.personal_image.path)


    def __str__(self):
        return self.email

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_short_name(self):
        return "%s" % (self.first_name)

    def has_perm(self, perm, obj=None):
        "Does the user have a specifit permissions ?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_active(self):
        return self.active

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_patient(self):
        return self.patient

    @property
    def is_doctor(self):
        return self.doctor


class Patient(models.Model):

    # TODO: Add doctor

    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    patient = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="Patient")
    supervised_by = models.ForeignKey(
        "Doctor", on_delete=models.CASCADE, blank=True)
    date_of_birth = models.DateField()
    age = models.PositiveIntegerField(default=0)
    gender      = models.CharField(max_length=6, choices=GENDER)
    weight      = models.FloatField()
    height      = models.FloatField()
    blood_group = models.CharField(max_length=4)
    country     = models.CharField(max_length=60)
    city        = models.CharField(max_length=60)
    street      = models.CharField(max_length=60)
    # image = models.ImageField("Patient personal image", )

    def __str__(self):
        return self.patient.email

    def get_patient_location(self):
        return f"{self.city}, {self.country}"


class Doctor(models.Model):
    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    doctor           = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Doctor')
    specialist       = models.CharField(max_length=255)
    gender           = models.CharField(max_length=6, choices=GENDER)


    def __str__(self):
        return self.doctor.email

class LabTechnician(models.Model):
    lab_technician              = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    test_case                   = models.TextField(max_length=255)
    test_name                   = models.TextField(max_length=255)
    test_cost                   = models.FloatField()

    def __str__(self):
        return f"{lab_technician.email}"

class Pharmacist(models.Model):
    pharmacist              = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    drug_presription        = models.TextField(max_length=255)
    drug_instruction        = models.TextField(max_length=512)
    drug_cost               = models.FloatField()

    def __str__(self):
        return f"{self.pharmacist.em}"

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model

from .models import Patient, Doctor, Pharmacist, LabTechnician

User = get_user_model()

# class UserCreationForm(forms.ModelForm):
#     # role = forms.ChoiceField(widget=forms.RadioSelect, choices=[(1, 'Patient'), (2, 'Doctor')])
#     class Meta:
#         model = User
#         fields = ('email', 'password, ')

class PatientCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
    class Meta:
        model  = Patient
        fields = '__all__'

class DoctorCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
    class Meta:
        model  = Doctor
        fields = '__all__'


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'role')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'active', 'admin', 'role')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class PatientHealthUpdateForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = (
            'date_of_birth',
            'age', 
            'gender',     
            'weight',     
            'height',     
            'blood_group',
            'country',    
            'city',       
            'street',     
        )

class PatientPersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'personal_image')


class DoctorUpdateForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = (
            'specialist',
            'gender',
        )

class DoctorPersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'personal_image')

templates/users/doctor/doctor_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Dashboard - {{ title }}</title>
    {% else %}
    <title>Doctor Dashboard</title>
    {% endif %}
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/dashboard_layout.css' %}">
</head>

<body>
    <div class="container">

        <div class="header">
            <nav>
                <ul>
                    <!-- <li class="username">Hello Dr.{{user.get_full_name}}</li> -->
                    <a href="{% url 'users:logout' %}"
                        class="logout inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
                        Logout
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                </ul>
            </nav>
        </div>
        
        <div class="sidebar">
    
            <header class="logo">
                <img src="{% static 'images/logo_transparent.png' %}" alt="logo">
            </header>
                
            <div>
                <ul>
                    <li>
                        <img class="link-icon" src="{% static 'images/icons/dashboard.png' %}" alt="">
                        <a class="nav-link {% if request.path == '/doctors/dashboard/' %} active {% endif %}" href="{% url 'users:doctor_dashboard' user.Doctor.id %}">Dashboard</a>
                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/user.png' %}" alt="">
                        <a class="nav-link" href="{% url 'users:doctor_profile' user.Doctor.id %}">Profile</a>

                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/appoinment.png' %}" alt="">
                        <a class="nav-link" href="{% url 'appointments:requested_appointments' %}">Appoinments</a>
                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/bell.png' %}" alt="">
                        <a class="nav-link" href="#">Notifications</a>
                    </li>

                    <li>
                        <img class="link-icon" src="{% static 'images/icons/drug-schedule.png' %}" alt="">
                        <a class="nav-link" href="#">Drug Schedule</a>
                    </li>

                </ul>
            </div>
        </div>
        


        <div class="content">
            {% block content %} {% endblock %}
        </div>




    </div>
</body>

</html>

templates/users/doctor/profile.html
{% extends 'users/doctor/doctor_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="border border-red-400 h-full">
    {% if messages %}
    {% for msg in messages %}
    {% if msg.tags == 'success' %}
    <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
        <!-- <strong class="font-bold"></strong> -->
        <span class="block sm:inline">{{msg}}</span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20">
                <title>Close</title>
                <path
                    d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
            </svg>
        </span>
    </div>
    {% elif msg.tags == 'error' %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <!-- <strong class="font-bold"></strong> -->
        <span class="block sm:inline">{{msg}}</span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20">
                <title>Close</title>
                <path
                    d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
            </svg>
        </span>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data" class="w-3/4 m-auto  my-4">

        <div class="h-28 bg-gradient-to-r from-green-400 to-blue-500"></div>
        <div class="w-24 h-24  m-auto m-2 -mt-16">
            <div class="w-20 h-16 m-auto">
                <img class="rounded-full" src="{{ user.personal_image.url }}" alt="user image">
            </div>
        </div>

        {% csrf_token %}
        <div class="flex flex-wrap justify-between mt-16">

            <div class="flex w-full mt-2 mb-2">
                <div class="border border-gray-200 w-2/5 m-auto"></div>
                <div class="text-xl text-gray-500 tracking-widest">Personal Data</div>
                <div class="border border-gray-200 w-2/5 m-auto mt-4"></div>
            </div>

            <div class="flex flex-wrap justify-around">
                <div class="flex flex-wrap flex-col">
                    <label for="id_first_name" class="text-lg text-gray-700 my-2">First Name</label>
                    <input type="text" name="first_name" value="{{p_form.first_name.value}}" maxlength="50" required
                        id="id_first_name"
                        class="border rounded-lg py-2 pl-2 text-gray-500 focus:text-gray-800 focus:outline-none focus:ring-1 focus:border-gray-400">
                </div>

                <div class="flex flex-wrap flex-col">
                    <label for="id_last_name" class="text-lg text-gray-700 my-2">Last Name</label>
                    <input type="text" name="last_name" value="{{p_form.last_name.value}}" maxlength="50" required
                        id="id_last_name"
                        class="border rounded-lg py-2 pl-2 text-gray-500 focus:text-gray-800 focus:outline-none focus:ring-1 focus:border-gray-400">
                </div>

                <div class="flex flex-wrap flex-col">
                    <label for="id_phone_number" class="text-lg text-gray-700 my-2">Phone Number</label>
                    <input type="text" name="phone_number" value="{{p_form.phone_number.value}}" maxlength="50" 
                        id="id_phone_number"
                        class="border rounded-lg py-2 pl-2 text-gray-500 focus:text-gray-800 focus:outline-none focus:ring-1 focus:border-gray-400">
                </div>

                <div class="flex flex-wrap mr-auto ml-8 mt-4">
                    <label for="id_personal_image" class="text-lg text-gray-700 my-2">Personal Image:</label>
                    <input type="file" name="personal_image" value="{{p_form.personal_image.value}}"
                        id="id_personal_image" class="mt-2 ml-2">
                </div>
            </div>

            <div class="flex w-full mt-6">
                <div class="border border-gray-200 w-2/5 m-auto mt-4"></div>
                <div class="text-xl text-gray-500 tracking-widest">Health Data</div>
                <div class="border border-gray-200 w-2/5 m-auto mt-4"></div>
            </div>

            <!-- Health form -->
            <div class="flex flex-wrap justify-around  w-full">
                <div class="flex flex-wrap flex-col ">
                    <label for="id_specialist" class="text-lg text-gray-700 my-2">Specialist</label>
                    <input type="text" name="specialist" value="{{doctor_form.specialist.value}}" maxlength="255" required
                        id="id_specialist"
                        class="border rounded-lg py-2 pl-2 text-gray-500 focus:text-gray-800 focus:outline-none focus:ring-1 focus:border-gray-400">
                </div>

                <div class="flex flex-wrap flex-col">
                    <label for="id_gender" class="text-lg text-gray-700 my-2">Gender</label>
                    <input type="text" name="gender" value="{{doctor_form.gender.value}}" maxlength="6" required id="id_gender" placeholder="M or F"
                        class="border rounded-lg py-2 pl-2 text-gray-500 focus:text-gray-800 focus:outline-none focus:ring-1 focus:border-gray-400">
                </div>
            </div>


        </div>
        <button type="submit"
            class="flex m-auto w-1/3 text-white text-xl bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-4">
            <span class="m-auto">Update</span>
        </button>
    </form>
</div>

{% endblock %}