dj_rpm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', users_views.landing_page, name='landing_page'),
    path('', include('users.urls', namespace='users')),  
    path('', include('appointments.urls', namespace='appointments')),  


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('user_role/', views.get_user_role, name='user_role'),
    path('signup/', views.signup_view, name='signup'),
    path('register_patient/', views.patient_signup_view, name='patient_signup'),
    path('register_doctor/', views.doctor_signup_view, name='doctor_signup'),
    
    # * Patient pages
    path('patient/<int:patient_id>/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/<int:patient_id>/profile/', views.patient_profile, name='patient_profile'),
    path('patient/<int:patient_id>/maps/', views.maps, name='maps'),

    # * Doctor pages
    path('doctor/<int:doctor_id>/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('doctors/delete_patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    path('doctor/<int:doctor_id>/profile/', views.doctor_profile, name='doctor_profile'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>RPM</title>
    {% endif %}
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}" type="text/css">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

</head>

<body>
    {% include 'navbar.html' %}

    {% block content %} {% endblock %}

    <!-- {% include 'footer.html' %} -->
</body>
</html>

templates/footer.html
{% load static %}

<style>
    .img {
        /* background-color: green; */
        width: 100px;
        margin-right: -30px;
    }
</style>

<footer class="text-gray-600 body-font mt-100">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
      <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
        <img class="img" src="{% static 'images/logo_transparent_without_text.png' %}" alt="logo">
        <span class="ml-3 text-xl">ElectroHealth</span>
      </a>
      <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2021 ElectroHealth —
        <a href="#" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@Abdulrhman</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </footer>

templates/landing_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ElectroHealth</title>

    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

    <!-- Import font-awesome -->
    <!-- <script src="https://kit.fontawesome.com/5a05ce74ab.js" crossorigin="anonymous"></script> -->


</head>

<body>
    <div class="container">
              <!-- Start header -->
        <header>
            <div class="logo">
                <img src="{% static 'images/logo_transparent.png' %}" alt="logo">
            </div>

            <nav class="navbar-nav">
                <ul>
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        {% if user.role == 'Doctor' %}
                        <a href="{% url 'users:doctor_dashboard' user.Doctor.id %}" >Dashboard</a>
                        {% elif user.role == 'Patient' %}
                        <a href="{% url 'users:patient_dashboard' user.Patient.id %}" >Dashboard</a>
                        {% else %}
                        <a href="http://127.0.0.1:8000/admin">Dashboard</a>
                        {% endif %}
                        <a href="{% url 'users:logout' %}">Logout</a>
                    <li>
                        {% else %}
                    <li>
                        <a href="{% url 'users:login' %}">Sign In</a>
                    </li>
                    <li>
                        <a href="{% url 'users:signup' %}" class="btn btn-primary signup">Sign Up Today</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

            <div id="header-section">
                <div class="text-area">
                    <h1>ElectroHealth</h1>
                    <div>
                        <p>
                            What if you can see your doctor and your full health data
                            while you are sitting on the couch, well <span>ElectroHealth</span>
                            is here to make it possible. with <span>ElectroHealth</span>
                            you can do much much more than that.
                        </p>
                        <ul>
                            <li><a href="#" class="btn btn-primary">Sign Up Now</a></li>
                            <li><a href="#" class="btn btn-secondary">Learn More</a></li>
                        </ul>
                    </div>
                </div>
                <div class="image-area">
                    <img src="{% static 'images/illustrations/001.svg' %}">
                </div>
            </div>

        </header>
        <!-- End header -->

        <!-- Start main -->
        <main>

            <div class="title-section">
                <h2 class="medium-title">What is ElectroHealth?</h2>
                <h1>Learn About ElectroHealth features in just minutes ... </h1>
            </div>
            <section class="features-section">
                <div class="features-area">

                    <div class="text-area">
                        <h1>No need for Regular <span style="color: tomato;"> Check-Ups</span> anymore!</h1>
                        <div>
                            <p>
                                ElectroHealth allows you to monitor your vital signs from home
                                by wearing some sensors that measure all your vital signs
                                and send it directly to your doctor.
                            </p>
                            <ul>
                        </div>
                    </div>

                    <div class="image-area">
                        <img src="{% static 'images/illustrations/003.svg' %}" alt="">
                    </div>


                    <div class="image-area">
                        <img src="{% static 'images/illustrations/005.svg' %}" alt="" style="margin-top: -50px;">
                    </div>

                    <div class="text-area">
                        <h1><span style="color: #f59c82;">appoinment</span> reserevations as a blink of an eye!</h1>
                        <div>
                            <p>
                                ElectroHealth not only for health monitoring, it is also
                                allow you to reserve an appoinment without going to anywhere!
                                Just a few clicks and booom.
                            </p>
                            <ul>
                        </div>
                    </div>

                    <div class="text-area">
                        <h1>No need to remember your <span style="color: #1c0aeba8;">Dosages</span> timing</h1>
                        <div>
                            <p>
                                All your dosages inclduing amount, frequency, and instructions
                                are saved and managed by your dotor, and also we will remaind you
                                about you Dosage time. so don't worry.
                            </p>
                            <ul>
                        </div>
                    </div>

                    <div class="image-area">
                        <img src="{% static 'images/illustrations/007.svg' %}" alt="">
                    </div>


                </div>
            </section>

            <!-- Cards -->

            <div class="title-section">
                <h2 class="medium-title">Why ElectroHealth?</h2>
            </div>

            <section class="cards-section">
                <div class="cards">
                    <div class="card">
                        <div class="card-icon"><img src="{% static 'images/icons/icon-003.svg' %}" alt=""></div>
                        <div class="card-content">
                            <p> Beacuse your Security is Our Top Priority
                                we have built the system by using the blockchain technology.</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-icon"><img src="{% static 'images/icons/icon-004.svg' %}" alt=""></div>
                        <div class="card-content">
                            <p>
                                You have wasted a lot of time by going to clincks for regular
                                check-ups, beacuse of that we have created this system to save your valuable time.
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-icon"><img src="{% static 'images/icons/icon-005.svg' %}" alt=""></div>
                        <div class="card-content">
                            <p>
                                Commuincate with you doctor instantly from anywhere and at any time.
                            </p>
                        </div>
                    </div>

                </div>

            </section>

        </main>
        <!-- End main -->

        <footer>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                <path fill="#273036" fill-opacity="1"
                    d="M0,128L40,154.7C80,181,160,235,240,261.3C320,288,400,288,480,261.3C560,235,640,181,720,138.7C800,96,880,64,960,58.7C1040,53,1120,75,1200,74.7C1280,75,1360,53,1400,42.7L1440,32L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z">
                </path>
            </svg>

        </footer>
    </div>
    <!-- {% include 'footer.html' %} -->
</body>

</html>

templates/navbar.html
{% load static %}

<style>
  .img {
    /* background-color: green; */
    width: 100px;
    margin-right: -30px;
  }
</style>


<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg> -->
      <img class="img" src="{% static 'images/logo_transparent_without_text.png' %}" alt="logo">
      <span class="ml-3 text-xl">ElectroHealth</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href="{% url 'landing_page' %}" class="mr-5 hover:text-gray-900">Home</a>
      <a href="#" class="mr-5 hover:text-gray-900">Contact</a>
      <a class="mr-5 hover:text-gray-900">About</a>
    </nav>
    {% if request.path == '/login/' %}
    <a href="{% url 'users:signup' %}"
      class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      Sign Up
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
      <a href="{% url 'users:login' %}"
        class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Log In
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% endif %}
  </div>
</header>